language: python
python:
- '3.5'
install: make install
script: make test
deploy:
  provider: pypi
  user: datacamp
  password:
    secure: W6gjvYjfbKDI1ODTHMZhr3vKGLsriY/zake3cEMJVh4e00GXXhN6ANVglJQ7HDSGLUKt9c2GxH1Ie8wJ23JSy0LlIbBb5Qk+UDxWHbBMbi9TsE5Gut2fkH2bMtfZC9O2IOEOxluLYXKlrQ0NWELpoxRSBCxjc2MfUed1xuUv9KHEBeqkYxJPQhrHPZYA1ekgAQLso4eCP2571m1WzF91LybEBuAX6MVPcLJ4TfDxZc7Da6+PBy61wPUtZAxWpbI0aARpPQZ3VYlcCVGgM/kIvOuJcbXQp5ngaibPM94XCYMs0TLifIPcADL+06Lh6UgklEuo/8LBvZjce27Tcf/xGCq0E8QXqV98rxargHkAdKxsgc/K41+m9iNWKpitBB6NYjo5HpVZK9wJOT1QHWsxKgtjjjokjsm8ooII1SQYfU/6Q3n48YUw4+mO0NK40tkLorAQJulWtUjPbNC/TIozuBK8YYc2IfVHA5Dv2kyASYSoCt9Pntqj5Jdi55LnYrTN44lxWfCPg3dKA2M3sHRi9dVbeRg4jIgYc6ne7QSsqfT41iY9uiwVn9wLWqPtFE9t8cPvzgFV78SnT6gOm74pRD4gILpQScT4tZDaTpsrA9pCmrrwwVO5OiXb7/SU8B9tJtUTQenjj4n3bdhHA046gF7ISABz35rOVa8GVeRlAdg=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/sqlwhat
  skip_upload_docs: true
