language: python
python:
- '3.5'
install: make install
script: make test
deploy:
  provider: pypi
  user: datacamp
  password:
    secure: ea5Lf5OC1848bQL82/iQxbGJ42/s86eK4+Evk4TuuictaqejSxDzsp1DUJRW0ELucFXzxSGDGsIZjtMRhYOsQPPSqMEHxqBqWEsl43LzhlBbJtQhRynUxWT8SHMcSW2PSm2eBl96b7npmOJUUte/tNQADG2K6fVb83cMx4pFoFBECzsGxOnGPtJTnD+kWQFuONp71Gu6uvax9/hdGpNHU2WnmXzJzH+mhhHmf/1L+jWOIx1BcFEmeI7IAuLmHATfHWrWtrMFCQWu/EP6M1o+tJ4fxM0Nt8FNxpjWnAnLjDNpI9UpSfZ89A8Ma/AgShDkvu9c4VOOd4gwF6A1d6dKsF4c1HWMYBCy50pdNEUUUMwCHogwYYYhZtfxApRKkW6THdKJJHqWViCpAGNGSSMaW061qbCja4kTjitjFKB8EUbpIfonKFQS/68VjuLnEsF1tsSJTndmp609uQTVGeGXb6i5FQ2QUXLluScwgQx9Yrc4ggKtdLUwBTeonrf+kIkMOVCKjuZ9nKX1/bRIMdViBL1NPKIJM67hF66L1lLlnXQVTAqTEmQxfNVy/9xYaqJvSvRgb/yyc6O/TaUFtYfDEfLF/HEEdAMudXGKKxfJtB7K3PZwHa0pwISTthRQjHqpWB7BCXrXy9//efisHBnQ52FdM4ztgsipMaCpKmOy/Ds=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/sqlwhat
  skip_upload_docs: true
